In [1]:
import numpy as np

# Arithmetic Operations 

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([10,20,30])
print(b)

[10 20 30]


In [4]:
a+b

array([11, 22, 33])

In [5]:
a-b

array([ -9, -18, -27])

In [6]:
a*b

array([10, 40, 90])

In [7]:
a/b

array([0.1, 0.1, 0.1])

In [12]:
s = np.array([10,20,30])
out = np.sum(s)
print(out)

60


In [16]:
s = np.array([10,20,30])
out = np.sum(s,initial=100)
print(out)

160


In [19]:
s = np.array([(10,20,30),(11,12,13),(1,2,3)])
out1 = np.sum(s,axis=1)
print(out1)

[60 36  6]


In [20]:
s = np.array([(10,20,30),(11,12,13),(1,2,3)])
out1 = np.sum(s,axis=0)
print(out1)

[22 34 46]


In [22]:
s = np.array([(10,20,30),(11,12,13),(1,2,3)])
out1 = np.sum(s,keepdims=True)
print(out1)

[[102]]


In [23]:
s = np.array([10,20,30])
sq = np.sqrt(s)
print(sq)

[3.16227766 4.47213595 5.47722558]


In [24]:
s = np.array([10,20,30])
sd = np.std(s)
print(sd)

8.16496580927726


In [27]:
s1 = np.array([10,20,30])
s2 = np.array([40,50,60])
vs = np.vstack((s1,s2))
print(vs)

[[10 20 30]
 [40 50 60]]


In [29]:
s1 = np.array([10,20,30])
s2 = np.array([40,50,60])
hs = np.hstack((s1,s2))
print(hs)

[10 20 30 40 50 60]


In [30]:
s1 = np.array([10,20,30])
ou = np.exp(s1)
print(ou)

[2.20264658e+04 4.85165195e+08 1.06864746e+13]


In [31]:
s = np.array([(10,20,30),(11,12,13),(1,2,3)])
out1 = np.ravel(s,order='C')
print(out1)

[10 20 30 11 12 13  1  2  3]


In [32]:
s = np.array([(10,20,30),(11,12,13),(1,2,3)])
out1 = np.ravel(s,order='F')
print(out1)

[10 11  1 20 12  2 30 13  3]


In [33]:
s1 = np.array([10,20,30])
out2 = np.log(s1)
print(out2)

[2.30258509 2.99573227 3.40119738]


# empty()

In [37]:
e = np.empty(3)
print(e)

[2.30258509 2.99573227 3.40119738]


In [40]:
e = np.empty([3,3])
print(e)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.56908569e-321]
 [7.56592337e-307 9.34588060e-307 3.62651150e-317]]


In [42]:
e = np.empty([3,3],dtype=int)
print(e)

[[10 20 30]
 [11 12 13]
 [ 1  2  3]]


In [43]:
e = np.empty([3,3],dtype=int,order='C')
print(e)

[[  0   1   0]
 [541 340   0]
 [768   0   0]]


In [45]:
z = np.zeros(3)
print(z)

[0. 0. 0.]


In [46]:
z = np.zeros([2,3])
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [47]:
z = np.zeros([2,3],dtype=float)
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [50]:
o = np.ones(4)
o

array([1., 1., 1., 1.])

In [51]:
o1 = np.ones([2,4])
o1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [52]:
o1 = np.ones([2,4],dtype=float)
o1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
ar = np.arange(11)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
ar = np.arange(1,11)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
ar = np.arange(1,11,2)
ar

array([1, 3, 5, 7, 9])

In [57]:
ar = np.arange(1,11,2,dtype=float)
ar

array([1., 3., 5., 7., 9.])

In [2]:
n = np.arange(11)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [3]:
n = np.arange(1,11)
print(n)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
n = np.arange(1,11,2)
print(n)

[1 3 5 7 9]


In [5]:
n = np.arange(1,11,2,dtype=float)
print(n)

[1. 3. 5. 7. 9.]


In [6]:
np.arange(-5,-1)

array([-5, -4, -3, -2])

In [7]:
np.arange(5,1,-1)

array([5, 4, 3, 2])

In [8]:
np.arange(1.5,5.8)

array([1.5, 2.5, 3.5, 4.5, 5.5])

In [10]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
list(range(1.2,10.5))

TypeError: 'float' object cannot be interpreted as an integer

# Random Function

# Random Integer numbers

In [14]:
from numpy import random

In [21]:
r = random.randint(101)
r

74

In [25]:
r = random.randint(101,size=6)
r

array([26, 73, 42, 66, 47, 26])

In [29]:
r = random.randint(101,size=(2,2))
r

array([[62, 36],
       [69, 22]])

# Random Float Numbers

In [31]:
r = random.rand()
r

0.664830062534846

In [38]:
r = random.rand(4)
r

array([0.6401334 , 0.65616038, 0.07450925, 0.11603183])

In [37]:
r = random.rand(2,3)
r

array([[0.57062188, 0.19102511, 0.04934752],
       [0.15076339, 0.75944174, 0.45704347]])

# Choice()

In [42]:
random.choice([1,2,3,4,5])

3

In [47]:
random.choice([1,2,3,4,5],size=3)

array([2, 3, 1])

In [48]:
random.choice([1,2,3,4,5],size=(3,3))

array([[1, 4, 3],
       [4, 1, 2],
       [5, 3, 2]])